export { getLatestInterval as getLatest } from './get-latest';
export { getNthLatest } from './get-nth-latest';
export { getByTime } from './get-by-time';
export { getByBoundary } from './get-by-boundary';
export { getAll } from './get-all';
export { getById } from './get-by-id';
export { create } from './create';
export { updateInterval as update } from './update-interval';
export { remove } from './remove';
export { getIntervalsCount as getCount } from './get-intervals-count';