GET http://localhost:9001/api/intervals
Accept: application/json

###

GET http://localhost:9001/api/intervals/4
Accept: application/json

###

GET http://localhost:9001/api/intervals/latest
Accept: application/json

###

GET http://localhost:9001/api/intervals/years
Accept: application/json

###

PUT http://localhost:9001/api/intervals/1
Content-Type: application/json

{
  "start": "2021-06-16T21:00:00.000Z",
  "end": "2021-06-22T20:59:59.000Z",
  "sum": 70,
  "latest": true,
  "id": 1
}

###

POST http://localhost:9001/api/intervals
Content-Type: application/json

{
  "start": "2021-06-23T21:00:00.000Z",
  "end": "2021-06-30T20:59:59.000Z",
  "sum": 70,
  "latest": true
}

###

GET http://localhost:9001/api/intervals/11/previous
Accept: application/json

###

GET http://localhost:9001/api/intervals/2/previous
Accept: application/json

### getYearlyIntervals

GET http://localhost:9001/api/intervals/years/2025
Accept: application/json
