name: Automation

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: npm ci
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
        continue-on-error: true
